[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x ./pocketbase/pocketbase && ./pocketbase/pocketbase serve --http=0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

